config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :transactions, only: [:create, :new, :index]

  namespace :admin, module: 'admin' do
    resources :transactions, only: :index
  end

  devise_for :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  class BallanceToLow < StandardError; end
  class ConsistencyError < StandardError; end

  scope :internal, -> { where(internal: true) }
  scope :non_internal, -> { where(internal: false) }

  validates :user, presence: true

  has_many :transactions_made,
    foreign_key: :charged_account_id,
    class_name: 'Transaction',
    inverse_of: :charged_account

  has_many :transactions_received,
    foreign_key: :target_account_id,
    class_name: 'Transaction',
    inverse_of: :target_account

  belongs_to :user

  before_save :check_negative_ballance!, unless: :internal
  before_save :check_transactions_consistency!

  def transactions
    (transactions_received + transactions_made).sort_by(&:created_at)
  end

  def transfer(amount, target_account, title: 'standard transaction')
    transaction do
      self.transactions_made.create!(
        charged_account: self,
        target_account: target_account,
        title: title,
        charged_account_ballance_before: self.ballance,
        target_account_ballance_before: target_account.ballance,
        amount: amount,
      )

      self.ballance -= amount
      target_account.ballance += amount

      self.save!
      target_account.save!
    end
    true
  end

  private

  def check_transactions_consistency!
    diff = transactions_received.pluck(:amount).sum - transactions_made.pluck(:amount).sum - ballance
    raise ConsistencyError, 'Ballance does not match transaction history' unless diff.zero?
  end

  def check_negative_ballance!
    if ballance < 0
      raise BallanceToLow, 'Unable to transfer money'
    end
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates :charged_account, :target_account,
    :charged_account_ballance_before, :target_account_ballance_before,
    :amount, :title, presence: true

  belongs_to :charged_account,
    class_name: 'Account',
    inverse_of: :transactions_made

  belongs_to :target_account,
    class_name: 'Account',
    inverse_of: :transactions_received

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :account
  validates :email, uniqueness: true
end

app/controllers/admin/transactions_controller.rb
module Admin
  class TransactionsController < ApplicationController
    before_action { authorize :transactions, :preview_all? }

    def index
      @transactions = Transaction.all
      respond_with @transactions
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  include Pundit

  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!

  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action { authorize :transactions, :manage_own? }
  before_action :set_transaction_form, only: [:new, :create]

  def index
    @transactions = TransactionPresenter.for_account(account)
    respond_with @transactions
  end

  def new
    respond_with @transaction_form
  end

  def create
    @transaction_form.create(transaction_params)
    respond_with @transaction_form, location: transactions_path
  end

  private

  def transaction_params
    params.require(:transaction_form).permit(:title, :receiver_id, :amount)
  end

  def set_transaction_form
    @transaction_form = TransactionForm.new account
  end

  def account
    @account ||= current_user.account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/transactions/index.html.haml
= link_to 'New', new_transaction_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th Date
      %th Amount
      %th Title
      %th From
      %th To
  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= transaction.created_at
        %td= transaction.amount
        %td= transaction.title
        %td= transaction.charged_account.user.email
        %td= transaction.target_account.user.email

app/views/application/_main_navbar.html.haml
%ul.nav.navbar-nav
  %li= link_to 'Transactions', transactions_path if policy(:transactions).manage_own?
  %li= link_to 'All transactions', admin_transactions_path if policy(:transactions).preview_all?

app/views/application/_user_navbar.html.haml
%ul.nav.navbar-nav.pull-right
  - if user_signed_in?
    %li= link_to "log out", destroy_user_session_path, method: :delete
  - else
    %li= link_to "log in", new_user_session_path

app/views/home/index.html.haml
%h1 Welcome to our Bank!
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis risus neque, non condimentum lorem lobortis a. Mauris sed turpis mauris. Nulla sodales commodo ex, sodales condimentum tellus condimentum quis. In bibendum odio sed metus pulvinar facilisis. Pellentesque consectetur urna condimentum lacus rhoncus, quis lacinia lorem congue. Fusce porttitor nulla ac condimentum luctus. Sed fermentum tortor in mauris ullamcorper, quis fermentum turpis tristique. Mauris ultricies tristique massa consectetur ultricies. Nunc blandit, arcu sit amet faucibus sagittis, libero massa vulputate risus, eu auctor augue velit quis tellus. Praesent pretium ante at elementum eleifend. Nullam feugiat, nibh sit amet fermentum aliquam, mauris sem malesuada justo, vitae scelerisque massa sapien nec arcu. Sed blandit nisi mattis sodales pharetra. Suspendisse dapibus tellus ut urna hendrerit commodo. Sed varius elit ut eleifend tristique. Nam ut metus malesuada mi scelerisque fermentum.
%p Proin mattis odio lectus, eget congue est iaculis et. Quisque augue nisl, rutrum ac vulputate id, vestibulum eget ex. Donec vitae augue condimentum, tempus nulla a, ultrices quam. Nunc id sodales lorem. Fusce quis lobortis nibh. Duis leo mi, condimentum in odio vel, lobortis faucibus urna. Duis purus quam, tincidunt id accumsan et, molestie sed felis. Curabitur porta tortor ut turpis interdum placerat. Aenean et neque at turpis dictum consequat eget euismod orci. Donec arcu erat, elementum ac tempus at, eleifend hendrerit quam. Duis ac lectus at est euismod feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam consequat, lacus a placerat efficitur, mauris nisi auctor ipsum, non aliquam elit ipsum consequat nibh. Vivamus quis leo in nibh malesuada congue posuere tincidunt sem.
%p Maecenas malesuada, ex nec tempus lacinia, eros nisi scelerisque eros, eu vestibulum nisl elit et eros. Duis lobortis risus euismod magna fermentum mattis. Aenean cursus quam sit amet vehicula convallis. Nunc sem mauris, efficitur nec ipsum non, finibus iaculis eros. Suspendisse feugiat ullamcorper tortor sed laoreet. Pellentesque eu dolor feugiat, scelerisque sem ac, fringilla lacus. Suspendisse vestibulum pretium neque, sit amet consequat justo. Phasellus sollicitudin sapien lacinia velit fermentum maximus. Pellentesque in ante at nulla iaculis convallis. Etiam luctus lacus felis, sed ultrices arcu fringilla vel.
%p Etiam aliquam fermentum est eu ornare. Maecenas lobortis elit fringilla tristique ultricies. Donec ac tellus eget dui tristique commodo nec in nulla. Integer sit amet ornare ex. Nunc aliquam massa at odio posuere rutrum. In ullamcorper leo a tortor molestie lobortis. Integer egestas ligula nec arcu posuere, a vestibulum sem egestas. Praesent quis quam nibh. Donec diam orci, fermentum id imperdiet sit amet, dignissim sed elit. Aliquam erat volutpat. Praesent facilisis efficitur tellus.

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Bank"
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to root_path, class: 'navbar-brand' do
          Bank
        .navbar-collapse.collapse.navbar-responsive-collapse
          = render 'main_navbar'
          = render 'user_navbar'

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Company 2016

app/views/transactions/index.html.haml
= link_to 'New', new_transaction_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th Date
      %th Amount
      %th Title
      %th From / To
  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= transaction.created_at
        %td= transaction.amount
        %td= transaction.title
        %td= transaction.from

app/views/transactions/new.html.haml
= simple_form_for @transaction_form, url: transactions_path do |f|
  = f.input :title
  = f.input :amount
  = f.input :receiver_id, collection: f.object.receivers, include_blank: false
  = f.submit 'Do Transaction', class: 'btn btn-primary'